- hosts: localhost
  
  tasks:
  - name: ensure dotfiles repository is present
    git:
      repo: https://github.com/saifulwebid/dotfiles.git
      dest: /home/saiful/dotfiles
      update: no
  
  - name: link gitconfig
    file:
      src: /home/saiful/dotfiles/git/gitconfig
      path: /home/saiful/.gitconfig
      state: link

  - name: ensure SSH directory is present
    file:
      path: /home/saiful/.ssh
      mode: g-rwx,o-rwx
      state: directory
  
  - name: link SSH configuration
    file:
      src: /home/saiful/dotfiles/ssh/config
      path: /home/saiful/.ssh/config
      state: link

  - name: apply Bash configuration
    lineinfile:
      path: /home/saiful/.bashrc
      line: ". ~/dotfiles/bash/bashrc"
      create: yes
