- hosts: localhost
  
  tasks:
  - name: ensure dotfiles repository is present
    git:
      repo: https://github.com/saifulwebid/dotfiles.git
      dest: /home/saiful/dotfiles
      update: no
  
  - name: link gitconfig
    file:
      src: /home/saiful/dotfiles/git/gitconfig
      path: /home/saiful/.gitconfig
      state: link
