- name: install apt-transport-https and ca-certificates
  become: yes
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    update_cache: yes

- name: add Cloud SDK distribution repository
  become: yes
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk

- name: import Google Cloud public key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: install Cloud SDK
  become: yes
  apt:
    name: google-cloud-sdk
    update_cache: yes

- debug:
    msg: "Manual step: you need to run `gcloud init`."
